package:
  name: acrosome-counter
  version: "1.0"

channels:
  - pytorch
  - defaults

dependencies:
  - python>=3.6
  - ninja
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - opencv
  - matplotlib
  - imgaug
  - pandas
  - pip:
    - git+https://github.com/facebookresearch/detectron2.git
